# Setup
title:        wuchang
tagline:      å·¥ä½œå­¦ä¹ ç¬”è®°
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       æå¿—æ
  url:        http://lizj.me 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown